/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package co.uk.gauntface.mobile.devicelab;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class integer {
        public static final int google_play_services_version=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
